### ISSUE TITLE
default values for the parameters in the API documentation

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-project.github.io#174]
Currently, the mandatory parameters in the API doc page have no default values. I suggest to provide some default values, so that a developer can just click "try it out" and get results.
E.g. for e-entity that is the dataset name and input text.

**Comment by bgrusdt** [comment]
I have added default values wherever it seemed to be useful. I didn't put any in all USER calls for instance, neither in PUT and DELETE calls. Where examples are given in the description, I did not copy them to the body or input field. I provided examples where I thought it was useful. Can we close this?

**Comment by ArneBinder** [comment]
I propose we should prefer defaults for the body then for the input parameter.

**Comment by ArneBinder** [comment]
[This](https://github.com/swagger-api/swagger-ui/issues/1980#issuecomment-187940745) looks alos interesting for body defaults.

**Comment by bgrusdt** [comment]
Also remove the input parameter from the documentation. 
Check in the swagger editor.

**Comment by ArneBinder** [comment]
@bgrusdt I fixed the swagger-ui, so that for the parameter **body** `schema.default` will be displayed (instead of simple `default`). Have a look at this example (taken from `POST /toolbox/convert/manage`) which should be rendered correctly:

```
        - name: body
          in: body
          required: true
          schema:
            type: string
            default: 'PREFIX itsrdf: <http://www.w3.org/2005/11/its/rdf#> SELECT ?charsequence ?entity WHERE {?charsequence itsrdf:taIdentRef ?entity}'
          description: A valid SPARQL SELECT query as plain text.
```
